spring.application.name=rental-property-backend

# =========================
# PostgreSQL (Neon)
# =========================
spring.datasource.url=jdbc:postgresql://ep-winter-math-aor9hxfv-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_gSlybBQ9eH0E
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# Hibernate (JPA)
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Server
# =========================
server.port=8080